### PR TITLE
Update announcements.go

### PR DESCRIPTION
**Pull request by forsinain43**
fixed spelling errors

### CODE REVIEW

**Comment by ericm** [comment]
@Strum355 @Thomas007G id say well need to test this on the staging server first lads

**Comment by Strum355** [comment]
What if its a covert date 🧐

**Comment by Thomas007G** [comment]
@ericm have you tested it with the dev-env yet?

**Comment by ericm** [comment]
@Thomas007G no but CI was able to clone it so that means it b nice
image

**Comment by Thomas007G** [comment]
@ericm THANK GOD

**Pull request merged**
